#!/usr/bin/python
# -*- coding: utf-8 -*-
# Version 0.1
from PyQt5 import QtCore, QtGui, QtWidgets
import time, dbase

# Funktion qtpydatum:
def qtpydatum():
    qtdatum = QtCore.QDate.currentDate()
    qtpydatum = qtdatum.toPyDate()
    qtpydatum = str(qtpydatum)
    return qtpydatum

# Funktion qtpytime
def qtpyzeit():
    qttime = QtCore.QTime.currentTime()
    qtpytime = qttime.toPyTime()
    qtpytime = str(qtpytime)
    return qtpytime

mb = QtWidgets.QMessageBox
dbase.create()
# Hauptteil
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setWindowIcon(QtGui.QIcon('strike.png'))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("")
        self.widgets = QtWidgets.QWidget(MainWindow)
        self.widgets.setObjectName("widgets")
        self.edit_id = QtWidgets.QTextEdit(self.widgets)
        self.edit_id.setGeometry(QtCore.QRect(140, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_id.setFont(font)
        self.edit_id.setObjectName("edit_id")
        self.edit_anzpers = QtWidgets.QTextEdit(self.widgets)
        self.edit_anzpers.setGeometry(QtCore.QRect(140, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_anzpers.setFont(font)
        self.edit_anzpers.setObjectName("edit_anzpers")
        self.cb_kinder = QtWidgets.QCheckBox(self.widgets)
        self.cb_kinder.setGeometry(QtCore.QRect(140, 350, 81, 17))
        self.cb_kinder.setObjectName("cb_kinder")
        self.cb_bahnwunsch = QtWidgets.QCheckBox(self.widgets)
        self.cb_bahnwunsch.setGeometry(QtCore.QRect(140, 400, 91, 17))
        self.cb_bahnwunsch.setObjectName("cb_bahnwunsch")
        self.edit_bahnwunsch = QtWidgets.QTextEdit(self.widgets)
        self.edit_bahnwunsch.setGeometry(QtCore.QRect(230, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_bahnwunsch.setFont(font)
        self.edit_bahnwunsch.setObjectName("edit_bahnwunsch")
        self.edit_kinder = QtWidgets.QTextEdit(self.widgets)
        self.edit_kinder.setGeometry(QtCore.QRect(230, 340, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_kinder.setFont(font)
        self.edit_kinder.setObjectName("edit_kinder")
        self.btn_reservieren = QtWidgets.QPushButton(self.widgets)
        self.btn_reservieren.setGeometry(QtCore.QRect(100, 600, 171, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_reservieren.setFont(font)
        self.btn_reservieren.setObjectName("btn_reservieren")
        self.edit_notizen = QtWidgets.QTextEdit(self.widgets)
        self.edit_notizen.setGeometry(QtCore.QRect(140, 450, 231, 101))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_notizen.setFont(font)
        self.edit_notizen.setObjectName("edit_notizen")
        self.strike_label = QtWidgets.QLabel(self.widgets)
        self.strike_label.setGeometry(QtCore.QRect(500, 0, 291, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.strike_label.setFont(font)
        self.strike_label.setObjectName("strike_label")
        self.vline1 = QtWidgets.QFrame(self.widgets)
        self.vline1.setEnabled(True)
        self.vline1.setGeometry(QtCore.QRect(370, 20, 31, 671))
        self.vline1.setMinimumSize(QtCore.QSize(31, 0))
        self.vline1.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline1.setObjectName("vline1")
        self.tf_sucheerg = QtWidgets.QTextBrowser(self.widgets)
        self.tf_sucheerg.setGeometry(QtCore.QRect(430, 120, 431, 211))
        self.tf_sucheerg.setObjectName("tf_sucheerg")
        self.edit_suche = QtWidgets.QTextEdit(self.widgets)
        self.edit_suche.setGeometry(QtCore.QRect(520, 70, 231, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_suche.setFont(font)
        self.edit_suche.setObjectName("edit_suche")
        self.hline1 = QtWidgets.QFrame(self.widgets)
        self.hline1.setGeometry(QtCore.QRect(410, 340, 471, 20))
        self.hline1.setFrameShape(QtWidgets.QFrame.HLine)
        self.hline1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.hline1.setObjectName("hline1")
        self.vline2 = QtWidgets.QFrame(self.widgets)
        self.vline2.setEnabled(True)
        self.vline2.setGeometry(QtCore.QRect(890, 20, 31, 671))
        self.vline2.setMinimumSize(QtCore.QSize(31, 0))
        self.vline2.setFrameShape(QtWidgets.QFrame.VLine)
        self.vline2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vline2.setObjectName("vline2")
        self.label_reg = QtWidgets.QLabel(self.widgets)
        self.label_reg.setGeometry(QtCore.QRect(400, 360, 331, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_reg.setFont(font)
        self.label_reg.setObjectName("label_reg")
        self.edit_vorname = QtWidgets.QTextEdit(self.widgets)
        self.edit_vorname.setGeometry(QtCore.QRect(500, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_vorname.setFont(font)
        self.edit_vorname.setObjectName("edit_vorname")
        self.edit_plz = QtWidgets.QTextEdit(self.widgets)
        self.edit_plz.setGeometry(QtCore.QRect(500, 530, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_plz.setFont(font)
        self.edit_plz.setObjectName("edit_plz")
        self.edit_adresse = QtWidgets.QTextEdit(self.widgets)
        self.edit_adresse.setGeometry(QtCore.QRect(500, 480, 241, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_adresse.setFont(font)
        self.edit_adresse.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.edit_adresse.setObjectName("edit_adresse")
        self.edit_nachname = QtWidgets.QTextEdit(self.widgets)
        self.edit_nachname.setGeometry(QtCore.QRect(740, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_nachname.setFont(font)
        self.edit_nachname.setObjectName("edit_nachname")
        self.btn_registrieren = QtWidgets.QPushButton(self.widgets)
        self.btn_registrieren.setGeometry(QtCore.QRect(570, 630, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_registrieren.setFont(font)
        self.btn_registrieren.setObjectName("btn_registrieren")
        self.label_res = QtWidgets.QLabel(self.widgets)
        self.label_res.setGeometry(QtCore.QRect(30, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_res.setFont(font)
        self.label_res.setObjectName("label_res")
        self.label_resstat = QtWidgets.QLabel(self.widgets)
        self.label_resstat.setGeometry(QtCore.QRect(930, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_resstat.setFont(font)
        self.label_resstat.setObjectName("label_resstat")
        self.tf_restat = QtWidgets.QTextBrowser(self.widgets)
        self.tf_restat.setGeometry(QtCore.QRect(930, 70, 321, 591))
        self.tf_restat.setObjectName("tf_restat")
        self.btn_refresh = QtWidgets.QPushButton(self.widgets)
        self.btn_refresh.setGeometry(QtCore.QRect(1160, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setObjectName("btn_refresh")
        self.cb_oneh = QtWidgets.QCheckBox(self.widgets)
        self.cb_oneh.setGeometry(QtCore.QRect(140, 260, 70, 17))
        self.cb_oneh.setObjectName("cb_oneh")
        self.cb_twoh = QtWidgets.QCheckBox(self.widgets)
        self.cb_twoh.setGeometry(QtCore.QRect(210, 260, 70, 17))
        self.cb_twoh.setObjectName("cb_twoh")
        self.label_id = QtWidgets.QLabel(self.widgets)
        self.label_id.setGeometry(QtCore.QRect(30, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.label_datum = QtWidgets.QLabel(self.widgets)
        self.label_datum.setGeometry(QtCore.QRect(30, 120, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_datum.setFont(font)
        self.label_datum.setObjectName("label_datum")
        self.label_beginn = QtWidgets.QLabel(self.widgets)
        self.label_beginn.setGeometry(QtCore.QRect(30, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_beginn.setFont(font)
        self.label_beginn.setObjectName("label_beginn")
        self.label_dauer = QtWidgets.QLabel(self.widgets)
        self.label_dauer.setGeometry(QtCore.QRect(30, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_dauer.setFont(font)
        self.label_dauer.setObjectName("label_dauer")
        self.label_anzpers = QtWidgets.QLabel(self.widgets)
        self.label_anzpers.setGeometry(QtCore.QRect(20, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_anzpers.setFont(font)
        self.label_anzpers.setObjectName("label_anzpers")
        self.label_notizen = QtWidgets.QLabel(self.widgets)
        self.label_notizen.setGeometry(QtCore.QRect(20, 450, 61, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_notizen.setFont(font)
        self.label_notizen.setObjectName("label_notizen")
        self.label_7 = QtWidgets.QLabel(self.widgets)
        self.label_7.setGeometry(QtCore.QRect(400, 73, 111, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_suchen = QtWidgets.QPushButton(self.widgets)
        self.btn_suchen.setGeometry(QtCore.QRect(780, 70, 75, 23))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_suchen.setFont(font)
        self.btn_suchen.setObjectName("btn_suchen")
        self.label_vname = QtWidgets.QLabel(self.widgets)
        self.label_vname.setGeometry(QtCore.QRect(410, 430, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_vname.setFont(font)
        self.label_vname.setObjectName("label_vname")
        self.label_adresse = QtWidgets.QLabel(self.widgets)
        self.label_adresse.setGeometry(QtCore.QRect(410, 480, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_adresse.setFont(font)
        self.label_adresse.setObjectName("label_adresse")
        self.label_telefon = QtWidgets.QLabel(self.widgets)
        self.label_telefon.setGeometry(QtCore.QRect(410, 580, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_telefon.setFont(font)
        self.label_telefon.setObjectName("label_telefon")
        self.label_name = QtWidgets.QLabel(self.widgets)
        self.label_name.setGeometry(QtCore.QRect(670, 430, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.edit_telefon = QtWidgets.QTextEdit(self.widgets)
        self.edit_telefon.setGeometry(QtCore.QRect(500, 580, 241, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_telefon.setFont(font)
        self.edit_telefon.setObjectName("edit_telefon")
        self.edit_stadt = QtWidgets.QTextEdit(self.widgets)
        self.edit_stadt.setGeometry(QtCore.QRect(740, 530, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.edit_stadt.setFont(font)
        self.edit_stadt.setObjectName("edit_stadt")
        self.label_plz = QtWidgets.QLabel(self.widgets)
        self.label_plz.setGeometry(QtCore.QRect(410, 530, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_plz.setFont(font)
        self.label_plz.setObjectName("label_plz")
        self.label_stadt = QtWidgets.QLabel(self.widgets)
        self.label_stadt.setGeometry(QtCore.QRect(670, 530, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_stadt.setFont(font)
        self.label_stadt.setObjectName("label_stadt")
        self.te_beginn = QtWidgets.QTimeEdit(self.widgets)
        self.te_beginn.setGeometry(QtCore.QRect(140, 171, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.te_beginn.setFont(font)
        self.te_beginn.setTime(QtCore.QTime(0, 0))
        self.te_beginn.setObjectName("te_beginn")
        self.te_dauer = QtWidgets.QTimeEdit(self.widgets)
        self.te_dauer.setGeometry(QtCore.QRect(140, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.te_dauer.setFont(font)
        self.te_dauer.setTime(QtCore.QTime(0, 0))
        self.te_dauer.setObjectName("te_dauer")
        self.de_datum = QtWidgets.QDateEdit(self.widgets)
        self.de_datum.setGeometry(QtCore.QRect(140, 121, 141, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.de_datum.setFont(font)
        self.de_datum.setDate(QtCore.QDate.currentDate())
        self.de_datum.setObjectName("de_datum")
        MainWindow.setCentralWidget(self.widgets)
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")

        self.retranslateUi(MainWindow)
        self.connectActions()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STRIKE"))
        self.cb_kinder.setText(_translate("MainWindow", "Kinder?"))
        self.cb_bahnwunsch.setText(_translate("MainWindow", "Bahnwunsch?"))
        self.btn_reservieren.setText(_translate("MainWindow", "Reservieren"))
        self.strike_label.setText(_translate("MainWindow", "Willkommen bei STRIKE!"))
        self.label_reg.setText(_translate("MainWindow", "Registrierung eines neuen Kunden:"))
        self.btn_registrieren.setText(_translate("MainWindow", "Registrieren"))
        self.label_res.setText(_translate("MainWindow", "Reservierung:"))
        self.label_resstat.setText(_translate("MainWindow", "Reservierungsstatus:"))
        self.btn_refresh.setText(_translate("MainWindow", "refresh"))
        self.cb_oneh.setText(_translate("MainWindow", "1 Stunde"))
        self.cb_twoh.setText(_translate("MainWindow", "2 Stunden"))
        self.label_id.setText(_translate("MainWindow", "ID:"))
        self.label_datum.setText(_translate("MainWindow", "Datum: "))
        self.label_beginn.setText(_translate("MainWindow", "Beginn:"))
        self.label_dauer.setText(_translate("MainWindow", "Dauer:"))
        self.label_anzpers.setText(_translate("MainWindow", "Anz. Personen:"))
        self.label_notizen.setText(_translate("MainWindow", "Notizen:"))
        self.label_7.setText(_translate("MainWindow", "Person suchen:"))
        self.btn_suchen.setText(_translate("MainWindow", "Suchen"))
        self.label_vname.setText(_translate("MainWindow", "Vorname:"))
        self.label_adresse.setText(_translate("MainWindow", "Adresse:"))
        self.label_telefon.setText(_translate("MainWindow", "Telefon:"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_plz.setText(_translate("MainWindow", "PLZ:"))
        self.label_stadt.setText(_translate("MainWindow", "Stadt:"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))

    def connectActions(self):
        self.btn_registrieren.clicked.connect(self.kunderegistrieren)
        self.btn_reservieren.clicked.connect(self.reservieren)
        self.btn_suchen.clicked.connect(self.personsuchen)
        self.btn_refresh.clicked.connect(self.refresh)

    def kunderegistrieren(self):
        regdatum = qtpydatum()
        vname = self.edit_vorname.toPlainText()
        name = self.edit_nachname.toPlainText()
        adresse = self.edit_adresse.toPlainText()
        plz = self.edit_plz.toPlainText()
        stadt = self.edit_stadt.toPlainText()
        telefon = self.edit_telefon.toPlainText()
        ergebnis = dbase.double(vname, name, adresse, plz, stadt, telefon)
        if ergebnis == 1:
            janein = mb.warning(MainWindow, "Kunde existiert bereits!",
            "Kunde existiert bereits. Identisch waren Name und vollständige Adresse. Möchten sie dennoch registrieren?",
            mb.Yes | mb.No, mb.No)
        else:
            janein = mb.No
        if janein == mb.Yes or ergebnis == 0:
            ergebnis = dbase.insertkunden(regdatum, vname, name, adresse, plz, stadt, telefon)
            if ergebnis < 99000:
                mb.information(MainWindow, "Fertig!",
                "Kunde wurde erfolgreich mit der ID {0} registriert.".format(ergebnis), mb.Ok)
            elif ergebnis > 99000 and ergebnis < 99999:
                mb.warning(MainWindow, "Datenbank fast voll!",
                "Die Datenbank umfasst mehr als 99.000 Einträge! Bitte entfernen nicht benötigte Einträge!", mb.Ok)
            else:
                mb.critical(MainWindow, "Datenbank voll!",
                "Die Datenbank umfasst mehr als 99.999 Einträge! Vorgang konnte nich abgeschlossen werden!", mb.Ok)
        else:
            mb.information(MainWindow, "Abgebrochen!", "Vorgang wurde abgebrochen.", mb.Ok)
        self.edit_vorname.setPlainText("")
        self.edit_nachname.setPlainText("")
        self.edit_adresse.setPlainText("")
        self.edit_plz.setPlainText("")
        self.edit_stadt.setPlainText("")
        self.edit_telefon.setPlainText("")

    def reservieren(self):
        empty = ""
        error = ""
        eid = self.edit_id.toPlainText()
        if eid == empty:
            error = "true"
        if eid != empty:
            ergebnis = dbase.existiertid(eid)
        if ergebnis == empty:
            error = "true"
            mb.critical(MainWindow, "ID existiert nicht!",
            "Es trat ein Fehler bei der Eingabe auf. Entweder existiert die ID nicht oder sie konnte nicht verarbeitet werden.", mb.Ok)
        personen = self.edit_anzpers.toPlainText()
        if personen == empty:
            error = "true"
        notizen = self.edit_notizen.toPlainText()
        if self.cb_kinder.isChecked():
            kinder = self.edit_kinder.toPlainText()
        else:
            kinder = 0
        if self.cb_bahnwunsch.isChecked():
            bahn = self.edit_bahnwunsch.toPlainText()
        else:
            bahn = 0
        if not (self.cb_oneh.isChecked() and self.cb_twoh.isChecked()):
            dauer = self.te_dauer.time()
            pydauer = dauer.toPyTime()
            pydauer = str(pydauer)
        if self.cb_oneh.isChecked() and self.cb_twoh.isChecked():
            error = "true"
        if self.cb_oneh.isChecked() and not self.cb_twoh.isChecked():
            pydauer = "01:00"
        if not self.cb_oneh.isChecked() and self.cb_twoh.isChecked():
            pydauer = "02:00"
        beginn = self.te_beginn.time()
        pybeginn = beginn.toPyTime()
        pybeginn = str(pybeginn)
        datum = self.de_datum.date()
        pydatum = datum.toPyDate()
        pydatum = str(pydatum)
        if error == empty:
            bahnfrei = dbase.bahnreservierungsstatus(pydatum, pybeginn, pydauer, bahn)
            if bahnfrei == 0:
                mb.critical(MainWindow, "Alle Bahnen belegt!",
                "Alle Bahnen sind zum gewählten Zeitpunkt bereits belegt.", mb.Ok)
            if bahnfrei != 0 and bahnfrei <= 6:
                dbase.insertjobs(eid, pydatum, pybeginn, pydauer, personen, kinder, bahnfrei, notizen)
                mb.information(MainWindow, "Fertig!",
                "Auftrag wurde reserviert. Zugewiesene Bahn ist {0}.".format(bahnfrei), mb.Ok)
            if bahnfrei == 7:
                dbase.insertjobs(eid, pydatum, pybeginn, pydauer, personen, kinder, bahn, notizen)
                mb.information(MainWindow, "Fertig!",
                "Auftrag wurde reserviert. Reservierung auf Bahn {0} konnte durchgeführt werden.".format(bahn), mb.Ok)
            if bahnfrei == 8:
                mb.critical(MainWindow, "Gewünschte Bahn nicht verfügbar!",
                "Die ausgewählte Bahn ist zu diesem Zeitpunkt bereits belegt.", mb.Ok)
        else:
            mb.critical(MainWindow, "Aktion nicht möglich!",
            "Es trat ein Fehler bei der Eingabe auf.", mb.Ok)
        self.cb_bahnwunsch.setChecked(False)
        self.cb_kinder.setChecked(False)
        self.cb_oneh.setChecked(False)
        self.cb_twoh.setChecked(False)
        zeit = QtCore.QTime(0,0)
        heutigesdatum = QtCore.QDate.currentDate()
        self.de_datum.setDate(heutigesdatum)
        self.te_dauer.setTime(zeit)
        self.te_beginn.setTime(zeit)
        self.edit_id.setPlainText("")
        self.edit_anzpers.setPlainText("")
        self.edit_notizen.setPlainText("")
        self.edit_kinder.setPlainText("")
        self.edit_bahnwunsch.setPlainText("")

    def personsuchen(self):
        empty = ""
        space = " "
        dspace = "  "
        personstr = ""
        suchfeld = self.edit_suche.toPlainText()
        if suchfeld != empty:
            self.tf_sucheerg.setPlainText("")
            arrayid = dbase.personsuchen(suchfeld)
            if arrayid != empty:
                for eid in arrayid:
                    personxy = dbase.idtoperson(eid)
                    for i in personxy:
                        personstr = personstr + space + i
                    personundid = str(eid) + dspace + personstr
                    self.tf_sucheerg.append(personundid)
                    personstr = ""
            else:
                mb.critical(MainWindow, "Fehler!", "Eingabe: Vorname Nachname", mb.Ok)
        else:
            mb.critical(MainWindow, "Fehler!", "Aktion nicht möglich: Feld ist leer!", mb.Ok)

    def refresh(self):
        adatum = qtpydatum()
        azeit = qtpyzeit()
        space = " "
        dspace = "  "
        self.tf_restat.setPlainText("")
        eid, aid = dbase.currentjobs(adatum, azeit)
        for i in range(len(eid)):
            personarray = dbase.idtopersonlite(eid[i])
            jobarray = dbase.idtojob(aid[i])
            person = personarray[0] + space + personarray[1]
            auftrag = jobarray[0] + space + jobarray[1] + dspace + person + dspace
            self.tf_restat.append(auftrag)
            personen = dspace + dspace + "Anzahl Personen: " + str(jobarray[2])
            self.tf_restat.append(personen)
            kinder = dspace + dspace + "Anzahl Kinder: " + str(jobarray[3])
            self.tf_restat.append(kinder)
            bahn = dspace + dspace + "Bahn Nummer: " + str(jobarray[4])
            self.tf_restat.append(bahn)
            notizen = dspace + dspace + "Anmerkungen: " + str(jobarray[5])
            self.tf_restat.append(notizen)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
